function(run_app expected)
    execute_process(COMMAND "${APP}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 120)
    if(NOT "${result}" STREQUAL "${expected}")
        message(FATAL_ERROR "Expected exit ${expected}, got ${result}\n${output}\n${errors}")
    endif()
    set(LAST_OUTPUT "${output}" PARENT_SCOPE)
    set(LAST_ERRORS "${errors}" PARENT_SCOPE)
endfunction()

function(run_fixture)
    execute_process(COMMAND "${FIXTURES}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT "${result}" STREQUAL "0")
        message(FATAL_ERROR "Fixture check failed: ${result}\n${output}\n${errors}")
    endif()
endfunction()

file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}/empty")
run_app(0 --help)
if(NOT LAST_OUTPUT MATCHES "Usage: mix-photo-export -input")
    message(FATAL_ERROR "Help used an unexpected executable name: ${LAST_OUTPUT}")
endif()
run_app(1)
if(NOT LAST_ERRORS MATCHES "Usage: mix-photo-export -input")
    message(FATAL_ERROR "Usage error used an unexpected executable name: ${LAST_ERRORS}")
endif()
run_app(1 "${WORK}/missing.mix")
run_app(1 "${WORK}/empty")
run_app(1 "${WORK}/empty" --quality 0)
run_app(1 "${WORK}/empty" --quality 101)
run_app(1 "${WORK}/empty" --quality 95junk)
run_app(1 "${WORK}/empty" --output)
run_app(1 -input)
if(NOT LAST_ERRORS MATCHES "Missing input file or directory")
    message(FATAL_ERROR "Missing input was not diagnosed: ${LAST_ERRORS}")
endif()
run_app(1 -input -output "${WORK}/unused")
if(NOT LAST_ERRORS MATCHES "Missing input file or directory")
    message(FATAL_ERROR "Output option was consumed as input: ${LAST_ERRORS}")
endif()
run_app(1 -input "${WORK}/empty" -output)
if(NOT LAST_ERRORS MATCHES "Missing output directory")
    message(FATAL_ERROR "Missing output was not diagnosed: ${LAST_ERRORS}")
endif()
run_app(1 -output -input "${WORK}/empty")
run_app(1 -input "${WORK}/empty" --input "${WORK}/empty")
file(WRITE "${WORK}/broken.mix" "This is not a compound document.")
run_app(1 "${WORK}/broken.mix" --output "${WORK}/broken-output")
file(GLOB broken_outputs "${WORK}/broken-output/*.jpg")
if(broken_outputs)
    message(FATAL_ERROR "An invalid document produced JPEG output")
endif()

run_fixture(create "${WORK}/generated")
file(GLOB generated_sources "${WORK}/generated/*")
foreach(original IN LISTS generated_sources)
    file(SHA256 "${original}" hash)
    list(APPEND generated_hashes "${hash}")
endforeach()
run_app(0 -input "${WORK}/generated" -output "${WORK}/generated jpg")
if(NOT LAST_OUTPUT MATCHES "3 converted, 0 skipped, 0 failed")
    message(FATAL_ERROR "Generated conversions failed: ${LAST_OUTPUT}")
endif()
foreach(name plain layers layers-image-000044)
    run_fixture(verify "${WORK}/generated jpg/${name}.jpg" fixture)
endforeach()
run_app(0 -input "${WORK}/generated" -output "${WORK}/generated jpg")
if(NOT LAST_OUTPUT MATCHES "0 converted, 3 skipped, 0 failed")
    message(FATAL_ERROR "Generated rerun failed: ${LAST_OUTPUT}")
endif()
foreach(original IN LISTS generated_sources)
    file(SHA256 "${original}" hash)
    list(POP_FRONT generated_hashes expected)
    if(NOT hash STREQUAL expected)
        message(FATAL_ERROR "Generated source was modified: ${original}")
    endif()
endforeach()

if(PHOTO_DIR)
    file(GLOB originals "${PHOTO_DIR}/*.mix" "${PHOTO_DIR}/*.MIX")
    if(NOT originals)
        message(FATAL_ERROR "No MIX fixtures found in ${PHOTO_DIR}")
    endif()
    foreach(original IN LISTS originals)
        file(SHA256 "${original}" hash)
        list(APPEND original_hashes "${hash}")
    endforeach()
    run_app(0 -input "${PHOTO_DIR}" -output "${WORK}/jpg")
    message(STATUS "${LAST_OUTPUT}")
    file(GLOB jpegs "${WORK}/jpg/*.jpg")
    list(LENGTH originals original_count)
    list(LENGTH jpegs jpeg_count)
    if(jpeg_count LESS original_count)
        message(FATAL_ERROR "Some documents did not produce an image")
    endif()
    foreach(jpeg IN LISTS jpegs)
        file(READ "${jpeg}" signature LIMIT 3 HEX)
        if(NOT signature STREQUAL "ffd8ff")
            message(FATAL_ERROR "Not a JPEG: ${jpeg}")
        endif()
        run_fixture(verify "${jpeg}")
        file(SHA256 "${jpeg}" hash)
        list(APPEND jpeg_hashes "${hash}")
    endforeach()
    run_app(0 "${PHOTO_DIR}" --output "${WORK}/jpg")
    if(NOT LAST_OUTPUT MATCHES "0 converted, ${jpeg_count} skipped, 0 failed")
        message(FATAL_ERROR "Rerun did not skip existing outputs: ${LAST_OUTPUT}")
    endif()
    foreach(jpeg IN LISTS jpegs)
        file(SHA256 "${jpeg}" hash)
        list(POP_FRONT jpeg_hashes expected)
        if(NOT hash STREQUAL expected)
            message(FATAL_ERROR "Existing JPEG was modified: ${jpeg}")
        endif()
    endforeach()
    foreach(original IN LISTS originals)
        file(SHA256 "${original}" hash)
        list(POP_FRONT original_hashes expected)
        if(NOT hash STREQUAL expected)
            message(FATAL_ERROR "Original was modified: ${original}")
        endif()
    endforeach()
    list(GET originals 0 sample)
    file(COPY_FILE "${sample}" "${WORK}/UPPER CASE.MIX")
    run_app(0 "${WORK}/UPPER CASE.MIX" --output "${WORK}/single" --quality 90)
    if(NOT EXISTS "${WORK}/single/UPPER CASE.jpg")
        message(FATAL_ERROR "Uppercase extension or spaced filename failed")
    endif()
    file(MAKE_DIRECTORY "${WORK}/input photos")
    file(COPY_FILE "${sample}" "${WORK}/input photos/sample.mix")
    run_app(0 -output "${WORK}/output photos" -input "${WORK}/input photos")
    if(NOT EXISTS "${WORK}/output photos/sample.jpg")
        message(FATAL_ERROR "Explicit folder options with spaces failed")
    endif()
    run_app(0 --input "${WORK}/input photos" --output "${WORK}/output photos")
    if(NOT LAST_OUTPUT MATCHES "0 converted, [1-9][0-9]* skipped, 0 failed")
        message(FATAL_ERROR "Double-dash aliases failed: ${LAST_OUTPUT}")
    endif()
endif()
message(STATUS "Regression checks passed")